import type { UtilityInputs } from './engine';

/** HTML modelinin varsayılan girdileri (100 MWp örneği). */
export function defaultUtilityInputs(): UtilityInputs {
  return {
    pname: '100 MWp Arazi GES + BESS Projesi',
    prep: '',
    firm: '',
    loc: '',
    mw: 100,
    capexUnit: 485,
    cur: 'tl',
    pmode: 'single',
    ppaY: 10,
    ppaCur: 'usd',
    ppaUSD: 60,
    ppaEsc: 0,
    ppaTL: 2700,
    fx0: 47,
    piTLa: 25,
    piTLb: 12,
    piUS: 2.5,
    fxMode: 'ppp',
    fxMan: 15,
    priceTL: 2500,
    priceReal: 0,
    opexShare: 70,
    bPcTL: 1200,
    bPdTL: 4000,
    spec: 1680,
    dcac: 1.25,
    p90: 94,
    scen: 'p50',
    avail: 99,
    curt: 1,
    degr: 0.4,
    life: 30,
    price: 55,
    priceEsc: 1,
    opexUnit: 6000,
    opexEsc: 2,
    replYear: 14,
    replCost: 20,
    salvage: 0,
    bessOn: false,
    bMW: 25,
    bMWh: 50,
    bCapexU: 180,
    bOpexU: 3,
    bRTE: 88,
    bCyc: 1,
    bDegr: 2,
    bAvail: 97,
    bPc: 25,
    bPd: 85,
    bAugY: 11,
    bAugC: 60,
    tax: 25,
    holiday: 0,
    depY: 10,
    vat: 0,
    vatM: 9,
    consM: 12,
    order: 'eq',
    debt: 70,
    kd: 7.5,
    ke: 15,
    tenor: 14,
    grace: 1,
    style: 'sculpt',
    target: 1.3,
    dsraM: 6,
    fee: 1.5,
    useWacc: true,
    rManual: 9,
    huawei: { count: 300, diff: 700, prodPct: 2, opexPct: 8 },
  };
}
